name: ci-chia-lib

on:
  push:
    branches:
      - master
    paths:
      - "lib-chia/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - master
    paths:
      - "lib-chia/**"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: |
          yarn test:lib
