name: ci-pawket-i18n

on:
  push:
    branches:
      - master
    paths:
      - "ui/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - master
    paths:
      - "ui/**"
      - ".github/workflows/**"

jobs:
  check-i18n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn

      - name: Build and Test
        run: |
          yarn check-i18n --ci
